x-hadoop-base: &hadoop_base
  image: apache/hadoop:3.4
  networks:
    - shared_net
  env_file:
    - ./hadoop/config

services:
  hdfs-namenode:
    <<: *hadoop_base
    container_name: namenode
    hostname: namenode
    command: ["hdfs", "namenode"]
    ports:
      - 9870:9870
    environment:
      ENSURE_NAMENODE_DIR: "/tmp/hadoop-root/dfs/name"
    # volumes:
    #   - ./hadoop/namenode:/opt/hadoop/data/nameNode
    #   - ./hadoop/config:/opt/hadoop/etc/hadoop
    #   - ./start-hdfs.sh:/start-hdfs.sh

  datanode:
    <<: *hadoop_base
    container_name: datanode
    command: ["hdfs", "datanode"]

  resourcemanager:
    <<: *hadoop_base
    container_name: resourcemanager
    hostname: resourcemanager
    command: ["yarn", "resourcemanager"]
    ports:
        - 8088:8088

  nodemanager:
    <<: *hadoop_base
    container_name: nodemanager
    command: ["yarn", "nodemanager"]